memory_limit = ${AWS_LAMBDA_FUNCTION_MEMORY_SIZE}M

opcache.enable_file_override = true
opcache.file_cache = /tmp
opcache.file_cache_consistency_checks = false
; opcache.file_cache_only = true
opcache.file_cache_read_only = true
opcache.file_update_protection = 0
opcache.jit = disable ; FIXME: https://github.com/php/php-src/issues/17770
opcache.log_verbosity_level = 3
opcache.validate_timestamps = 0
