name: push

on: push

jobs:
  layer:
    name: Layer
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Download composer.phar
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          gh release --repo composer/composer download --pattern composer.phar
          gh attestation verify --repo composer/composer composer.phar
      - name: Composer
        uses: ./.github/actions/php
      - run: |
          ln -s . zero
          zip -rX9 zero.zip zero/bootstrap.php zero/vendor zero/wordpress zero/wp-config.php
      - uses: actions/upload-artifact@v6
        with:
          name: zero.zip
          path: zero.zip
