name: push

on: push

jobs:
  layer:
    name: Layer
    runs-on: ubuntu-latest
    container:
      image: bref/php-85-dev:v3
      volumes:
        - ${{ github.workspace }}:/opt/zero
    steps:
      - run: dnf -y install findutils gzip tar
      - uses: actions/checkout@v6
      # FIXME: perhaps publish a separate arch-dependent layer?
      - run: mkdir -p bref/extensions && cp /opt/bref/extensions/xdebug.so bref/extensions/
      - name: Composer
        uses: ./.github/actions/composer
      - name: Prime the opcache
        run: ./.github/opcache.sh
      - run: ln -s . zero
      - uses: actions/upload-artifact@v6
        with:
          name: zero
          path: |
            bref
            zero/bootstrap.php
            zero/opcache
            zero/vendor
            zero/wordpress
            zero/wp-config.php
